<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'TAPTestEngine' => 'tap/TAPTestEngine.php',
  ),
  'function' => array(
    'unit_test_engine_get_lines' => 'tap/TAPTestEngine.php',
    'unit_test_engine_sort_lines' => 'tap/TAPTestEngine.php',
  ),
  'xmap' => array(
    'TAPTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
